version: '3.8'
services:
  invoices-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5843:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
